<?

print "Applying tag rules\n"; flush();

$qr = CCDatabase::Query('SELECT upload_id,upload_extra FROM cc_tbl_uploads');
$count    = 0;
$table    = new CCTable('cc_tbl_uploads','upload_id');
$tagtable = new CCTable('cc_tbl_tags','tags_tag');
$tagcols  = array( 'tags_tag', 'tags_type' );

while( $row = mysql_fetch_array($qr) )
{
    $ex = unserialize($row['upload_extra']);
    // [ccud] => media,acappella
    // [usertags] => female_vocals,melody
    // [systags] => sampling_plus,audio,mp3,44k,mono,128kbps
    if( empty($ex['usertags']) )
        continue;

    $atags = split(',',$ex['usertags']);

    if( !empty($atags) )
    {
        // apply aliases...
        
        $stags = "'" . join("', '", $atags) . "'";
        $sql = "SELECT tag_alias_tag,tag_alias_alias FROM cc_tbl_tag_alias WHERE tag_alias_tag IN ({$stags})";
        $aliases = CCDatabase::QueryRows($sql);

        // the new tags (aliases) may not be in the tags db and they need to be (sigh)
        $updates = array();
        
        if( !empty($aliases) )
        {
            $new_user_tags = array();
            foreach($aliases as $alias)
            {
                $newtags = split(',',$alias['tag_alias_alias']);
                foreach( $newtags as $NT )
                {
                    $NT = trim($NT);
                    if( !empty($NT) )
                    {
                        $new_user_tags[] = $NT;
                        $updates[] = array( $NT, CCTT_USER );
                    }
                }
                $replaces[] = $alias['tag_alias_tag'];
            }
            $atags = array_unique( array_merge( $new_user_tags, array_diff($atags,$replaces) ));

            $tagtable->InsertBatch($tagcols,$updates,true);            
        }
    }

    // weed out system tags...

    if( !empty($atags) )
    {
        $userBit = 0xFFF; // CCTT_USER;
        $stags = "'" . join("', '", $atags) . "'";
        $sql = "SELECT tags_tag FROM cc_tbl_tags WHERE (tags_type & {$userBit}) <> 0 AND tags_tag IN ({$stags})";
        $atags = CCDatabase::QueryItems($sql);
    }
    
    $ex['usertags'] = join(',',array_unique($atags));
    $user_tags = join(',', array_unique( split(',',join(',', array($ex['ccud'],$ex['usertags'],$ex['systags'] )))));
    $uargs = array();
    $uargs['upload_id']    = $row['upload_id'];
    $uargs['upload_tags']  = $user_tags;
    $uargs['upload_extra'] = serialize($ex);
    $table->Update($uargs);
    
    if(++$count % 100 == 0) print '.';
    if($count % 400 == 0) flush();
    if($count % 8000 == 0) print "\n";
}

print "\nCalculating tag pairs\n";

$sql = array();

$sql[] = 'DROP TABLE IF EXISTS tptemp';
$sql[] = 'CREATE TABLE tptemp (tag_pair varchar(255),tag_pair_tag varchar(255) )';
$sql[] = 'DROP TABLE IF EXISTS tagtemp';
$sql[] = 'CREATE TABLE tagtemp (tag varchar(255))';

CCDatabase::Query($sql);

$qr       = CCDatabase::Query('SELECT upload_tags FROM cc_tbl_uploads');
$table    = new CCTable('tptemp','tag_pair');
$subtypes = array('remix','sample','acappella','contest_source','contest_sample','original','extended_mix','site_promo');
$filt     = array_merge($subtypes, array('media','audio'));
$cols     = array( 'tag_pair', 'tag_pair_tag ');

$ttable   = new CCTable('tagtemp','tag');
$tcols    = array( 'tag' );

$count = 0;
$misses = array();
while( $row = mysql_fetch_array($qr) )
{
    $tags  = array_filter(split(',',$row[0]));

    $tarr = array();
    foreach($tags as $T)
        $tarr[] = array($T);
    $ttable->InsertBatch($tcols,$tarr);
    
    $types = array_intersect($tags,$subtypes);
    $tags  = array_diff( $tags, $filt );
    if( empty($types) )
    {
        $misses[] = $row[0];
       
    }
    foreach( $types as $type )
    {
        $batch = array();
        foreach( $tags as $tag )
        {
            $batch[] = array( $type, $tag );
        }
        $table->InsertBatch( $cols, $batch );
    }
    if( ++$count % 100 == 0 ) print '.';
    if($count % 400 == 0) flush();
    if($count % 8000 == 0) print "\n";
}

print "\nCleaning up pair\n";
$sql = array();
$sql[] = 'DELETE FROM cc_tbl_tag_pair';
$sql[] =<<<EOF
        INSERT INTO cc_tbl_tag_pair
          SELECT tag_pair, tag_pair_tag, COUNT(*) as tag_pair_count
          FROM tptemp
          GROUP BY tag_pair,tag_pair_tag
EOF;
$sql[] = 'DROP TABLE tptemp';
$sql[] = 'UPDATE cc_tbl_tags SET tags_count = 0';
CCDatabase::Query($sql);

print "Recalculating tag counts\n";
$tagt = new CCTable('cc_tbl_tags','tags_tag');
$qr = CCDatabase::Query('SELECT COUNT(*) as tags_count, tag as tags_tag FROM tagtemp GROUP BY tag');
while( $row = mysql_fetch_assoc($qr) )
{
    $tagt->Update($row,true);
}
$sql = array();
$sql[] = 'DELETE FROM cc_tbl_tags WHERE tags_count < 1 AND tags_type = ' . CCTT_USER;
$sql[] = 'DROP TABLE tagtemp';
$sql[] = 'UPDATE cc_tbl_tags SET tags_tag = LOWER(tags_tag)'; // some tags ended up upper case which breaks INSERT
CCDatabase::Query($sql);

//print "missing: ";
//var_dump($misses);

print "done\n";

/*
 save the rules:
 
12_string_guitar=>12_string,guitar
12string=>12_string,guitar
12_string=>12_string,guitar
12_string_acoustic_guitat=>12_string,guitar
12string_guitar=>12_string,guitar
1920s=>20s
two_step=>2_step
2step=>2_step
jazzstep=>2_step,jazzy
jazz_step=>2_step,jazzy
1940s=>40s
50s_pop=>50s,pop
1960s=>60s
60_s_psychedelia=>60s,psychedelic
70_s=>70s
70ies=>70s
remember_1975=>70s
70s_disco=>70s,disco
70s_nostalgia=>70s,nostalgia
1970_prog=>70s,progressive
70s_rock_hero_on_wierd_in=>70s,rock
70s_rock_ballad=>70s,rock,ballad
80ies=>80s
80s_club=>80s,club
80s_rock_ballad=>80s,rock,ballad
80s_soul=>80s,soul
8bit=>8_bit
90ies=>90s
abstrak=>abstract
abstract_audio=>abstract
abstrak_soul_workshop=>abstract,soul
absinthe=>absynth
rap_accapella=>acappealla,rap
a_capella=>acappella
pella=>acappella
acapella=>acappella
a_cappella=>acappella
accapella=>acappella
accordeon=>accordian
solo_accordion=>accordian
accordion=>accordian
accordians=>accordian
achin=>ache
acid_jazzy=>acid_jazz
acidjazz=>acid_jazz
acidpro=>acid_pro
acoutstic=>acoustic
acoustic_slide_slow=>acoustic
acoustic_noodling_05=>acoustic
acousitic=>acoustic
acustik=>acoustic
acustic=>acoustic
acoustig_guitar=>acoustic
acoustic_sample=>acoustic
acoustic_noodling_03=>acoustic
accoustic=>acoustic
akustik=>acoustic
acoustic_gutar=>acoustic,acoustic_guitar
acoustic_guitar_harmonics=>acoustic,guitar
acoustic_guitar_loop_live=>acoustic,guitar
acousitic_guitar=>acoustic,guitar
acoustic_guitar_bass_elec=>acoustic,guitar,bass
latin_acoustic_guitar_cho=>acoustic,guitar,latin
upright_piano=>acoustic,piano,upright
acoustic_picking_10=>acoustic,picking
acoustic_picking_15=>acoustic,picking
african=>africa
afropop=>africa,afro_pop
africa_do_sul=>africa,do_sul
afrika=>africa,south_africa
afrikkan=>africa,south_africa
aggresive=>aggressive
agressiv=>aggressive
agressive=>aggressive
akai_s=>akai
alterntive=>alternative
altenative=>alternative
rock_alternative=>alternative_rock
alt_country_fusion=>alt_country
beginner=>amateur
ambient_96bpm=>ambient_flavor
ambiant=>ambient_flavor
ambience=>ambient_flavor
ambiental=>ambient_flavor
electronic_ambient_voice=>ambient_flavor
ambient_music=>ambient_flavor
ambiance=>ambient_flavor
poppy_ambient_dub=>ambient_flavor
remix_ambient_minimal_bre=>ambient_flavor
background_ambient=>ambient_flavor
concrete_ambient=>ambient_flavor
ambinet=>ambient_flavor
bass_ambient=>ambient_flavor,bass
analog_ambient_hiss_chill=>ambient_flavor,chill
electronic_ambient_chill=>ambient_flavor,chill
ambient_chill=>ambient_flavor,chill
dark_ambient_chill=>ambient_flavor,dark,chill
down_tempo_ambient_male_v=>ambient_flavor,downtempo
feedback_ambient_noise_gu=>ambient_flavor,guitar
ambient_soundscape_ocean=>ambient_flavor,ocean,soundscape
ambient_pads=>ambient_flavor,pads
pop_ambient=>ambient_flavor,pop
ambiance_7=>ambient_style
abient=>ambient_style
american_theme=>american
ameritronica=>american
amusment=>amusement
analogue=>analog
ancient_songs=>ancient_music
angry_young_criminal_remi=>angry
angsty_highschool_song=>angst
animal_noises=>animal
anthem_style=>anthem
apologize=>apology
arpegio=>arpeggiator
arpeggiator=>arpeggiator
arpeggiators=>arpeggiator
arpeggio_synth_synth1_ele=>arpeggiator
arpegios=>arpeggiator
arpeggios=>arpeggiator
arpeggio=>arpeggiator
arp=>arpeggiator
arpeggiation=>arpeggiator
atmoshpere=>atmospheric
atmostpheric=>atmospheric
atmospherical=>atmospheric
electronic_atmospheric_ex=>atmospheric
atmosphere=>atmospheric
garde=>avant_garde
avant=>avant_garde
avante_garde=>avant_garde
avantgarde=>avant_garde
avante=>avant_garde
avant_guarde=>avent_garde
bagpipe=>bagpipes
balkan_folk_live_samples_=>balkan
ballad_swank_love=>ballad
ballad_style=>ballad
balad=>ballad
american_ballad=>ballad,american
ballerina=>ballet
bark=>barking
bass_loop=>bass
bass_guitar=>bass
bassline=>bass
bassguitar=>bass
basstring=>bass
grime_bass=>bass
basses=>bass
bass_strings_dub=>bass
tuned_bass=>bass
incredible_bass_playing=>bass
sir_ra_bass=>bass
bass_line=>bass
n_bass=>bass
slinky_bass=>bass
bass_heavy=>bass
bass_and_more_bass=>bass
chopper_bass=>bass
heavy_bass=>bass
phusion_bass=>bass
thump_bass=>bass
pitch_shifted_bass=>bass
sub_bass=>bass
6_string_bass=>bass,6_string
acidbass=>bass,acid
upright=>bass,acoustic
upright_bass=>bass,acoustic
double_bass=>bass,acoustic
acoustic_bass=>bass,acoustic_bass
agressive_bass=>bass,aggressive
blues_brass=>bass,blues
blues_bass=>bass,blues
bowed_bass=>bass,bowed
deep_bass=>bass,deep
distorted_bass=>bass,distorted
bass_dnb=>bass,dnb
electric_bass=>bass,electric
electric_bass_guitar=>bass,electric_bass
farty_bass=>bass,farty
fretless_bass=>bass,fretless
funk_bass=>bass,funk
funky_bass=>bass,funky
fuzz_bass=>bass,fuzz,distorted
bass_jungle=>bass,jungle
miami_bass=>bass,miami
nasty_bass=>bass,nasty
fender_precision=>bass,precision
fender_precision_bass=>bass,precision
precicison_bass_guitar=>bass,precision
bass_psychedelic_raga_roc=>bass,psychedelic,rock
pump_bass=>bass,pump
retro_bass=>bass,retro
slap_bass=>bass,slap
slapbass=>bass,slap
snakey_bass=>bass,snakey
bass_synthesizer=>bass,synthesizer
analog_bass__synthesizer=>bass,synthesizer
twangy_bass=>bass,twangy
walking_bass=>bass,walking
wobble_bass=>bass,wobble
basson=>bassoon
bassclarinette=>bass_clarinet
bassclarinet=>bass_clarinet
battle_track=>battle
bbe=>bbe_music
beachside=>beach
beachy_country=>beach
beat_box=>beatbox
beat_vocal=>beat_poetry
beep=>beeps
bellydancer=>bellydance
bhangra_remix=>bhangra
big_beats=>big
big_dog=>big
big_feather_headress=>big
big_band_swing=>big_band,swing
bigbeat=>big_beat
electronic_big_beat=>big_beat
birds_chirping=>birds
birds_singing=>birds
birth=>birthday
birthdaysong=>birthday
birthday_girl=>birthday
birthday_song=>birthday
blippy=>blips
blocks=>block
blocked=>block
blue_grass=>bluegrass
blues_espacial=>blues
blues_ish=>blues
blues_pop_ballad=>blues,pop,ballad
nova=>bossa_nova
bossa=>bossa_nova
bossnova=>bossa_nova
bouncey=>bouncy
sucks=>brad_sucks
brad=>brad_sucks
brass_section=>brass
brazilian_songs=>brazil
brasil=>brazil
brazilian=>brazil
brazilian_song=>brazil
brazillian=>brazil
africa_brasil=>brazil,africa
brazilian_spice=>brazil,spice
breakcore_step_core_core=>break,breakcore
breakbeats=>breaks
breakers=>breaks
break=>breaks
breakbeat=>breaks
breakz=>breaks
break_beat=>breaks
electro_breakbeat=>breaks
beakz=>breaks
progressive_breaks=>breaks,progressive
broken_electro_melodico_b=>broken
caixa_forum=>caixa
cajon_loop_100bpm=>cajon
chello=>cello
electric_cello=>cello,electric
elec_cello=>cello,electric
peltic=>celtic
kids=>children
female_child_vocal=>children
child_vocals=>children
3_year_old=>children
child=>children
female_child_vocals=>children
chilly=>chill
chill_out=>chill
chillout=>chill
chilling_looping=>chill
chilled=>chill
chill_out_electronic_danc=>chill
electronic_chill_out=>chill
to_chill=>chill
from_chill_to_thrill=>chill,thrill
choral=>choir
chorale=>choir
gospel_choir=>choir,gospel
acoustic_christmas=>christmas,acoustic
clarnet=>clarinet
clav=>clavinet
electriclav=>clavinet
click=>clicks
sfx_clicks_pops=>clicks
electronic_club=>club
conga=>congas
congo=>congas
contrebasse=>contrabass
a_little_bit_country=>country
crammed_discs=>crammed
more_than_crunk=>crunk
crunky_rap=>crunk,rap
cutup=>cut_up
crash=>cymbals,crash
ride=>cymbals,ride_cymbal
dancefloor=>dance
distorded=>distorted
distorsion=>distortion
distorted=>distortion
drum_bass=>dnb
drumand_bass=>dnb
d_n_b=>dnb
drumnbass=>dnb
drums_and_bass=>dnb
drum_and_bass=>dnb
classical_drum_and_bass=>dnb
bass_and_drum=>dnb
drum__and__bass=>dnb
drum_n_bass=>dnb
d_b=>dnb
dum_n_bass=>dnb
drum_n_bass_atmospheric=>dnb,atmospheric
phat_dnbnguitar=>dnb,guitar
drum_and_bass_jungle_heav=>dnb,jungle
drum_and_bass_dnb_jungle_=>dnb,jungle
soundscape_drum_n_bass=>dnb,soundscape
down_tempo=>downtempo
downtemp=>downtempo
electro_funk_downtempo=>downtempo,funk
dream=>dreamy
dreams=>dreamy
dream_pop=>dreamy,pop
drones=>drone
8_drumbeat=>drums
808_drums=>drums,808
real_drums=>drums,acoustic
live_drums=>drums,acoustic,live
blues_drums=>drums,blues
electronic_drums_electro=>drums,electronic
drums_groove_funk=>drums,funky
funkyredrum=>drums,funky
funky_drumtrack=>drums,funky
funky_drum_loop_80bpm=>drums,funky
jazz_drums=>drums,jazz
jazz_drum=>drums,jazzy
loops_of_drums=>drums,loops
reggae_drums=>drums,reggae
rock_drums=>drums,rock
electro_dub_tech_experime=>dub
electro_dub=>dub,electro
mountain_dulcimer=>dulcimer,mountain
echoes=>echo
audio_special_fx=>effects
fxs=>effects
elektric=>electric
groovy_electro=>electro
electro_loop=>electro
pseudo_electro=>electro
hardelectro1_kit=>electro
elettro=>electro
electro_club_house=>electro,club
electro_hop=>electro,hip_hop
electro_pop=>electro,pop
soulful_electro_pop=>electro,pop
electropunk=>electro,punk
electro_punk=>electro,punk
electro_rock=>electro,rock
electrock=>electro,rock
electro_hardtechfunk=>electro,techno
electronic_music=>electronic
synth_electronics=>electronic
electroonic=>electronic
electrononic=>electronic
electrinoc=>electronic
electroic=>electronic
electornic=>electronic
electronic_voices=>electronic
electronic_farm=>electronic
electronic_loops=>electronic
electonic=>electronic
digital_beat_electronic_p=>electronic
elelectronic=>electronic
electronic_remix_synth_lo=>electronic
electronic_minimal_techno=>electronic,techno
skate_skating_electronica=>electronica
electoclash=>electronica
electonica=>electronica
eletronica=>electronica
electornica=>electronica
jazztronica=>electronica,jazzy
progressive_electronica=>electronica,progressive
etno=>ethno
evocatie=>evocative
alt_experimental=>experimental
female_bass=>female,bass
female_drums=>female,drums
female_guitars=>female,guitar
female_rock=>female,rock
female_vocals_big_beat_fu=>female_vocals
female_backup=>female_vocals
vocal_female=>female_vocals
female_backup_vox=>female_vocals
electronic_female_vocals=>female_vocals
female_vocalizing=>female_vocals
femmale_vocals=>female_vocals
female_vocals_cancion_arg=>female_vocals
female_volcals=>female_vocals
female_acapella=>female_vocals
loop_female_vocals=>female_vocals
that_were_female_vocals=>female_vocals
female_vocals_short_file_=>female_vocals
female_vocals_electronic_=>female_vocals
female_vocals_hopeless_bo=>female_vocals
source_track_for_female_v=>female_vocals
infaredhaze_female_vocals=>female_vocals
female_artist=>female_vocals
women=>female_vocals
female_vocal=>female_vocals
female_a_capella=>female_vocals
female_vox=>female_vocals
femal_vocals=>female_vocals
midtempo_chill_female_voc=>female_vocals
female=>female_vocals
female_voices=>female_vocals
female_voice=>female_vocals
female_singer=>female_vocals
femalevocal=>female_vocals
woman=>female_vocals
female_vocals__minimal=>female_vocals
females_vocals=>female_vocals
female_vocals_arps=>female_vocals,arpeggiator
female_vocals_classical=>female_vocals,classical
remix_female_voice_downte=>female_vocals,downtempo
electronic_female_vocal=>female_vocals,electronic
vocals_female_hip_hop=>female_vocals,hip_hop
female_vocal_loops=>female_vocals,loops
female_male_vocals=>female_vocals,male_vocals
female_vocalsstrings=>female_vocals,orchestral
female_rap=>female_vocals,rap
female_rapper=>female_vocals,rap
female_spokenword=>female_vocals,spoken_word
female_vocal_spoken_worde=>female_vocals,spoken_word
female_spoken_word=>female_vocals,spoken_word
field=>field_recording
field_recordings=>field_recording
flutes=>flute
flute_melody=>flute
forest_flutes=>flute
bansuri_flute=>flute,bansuri
celtic_flute=>flute,celtic
chipped_flute=>flute,chipped
rusty_flute=>flute,distorted
indian_bansuri_flute=>flute,indian
indian_flute=>flute,indian
jazzflute=>flute,jazz
pan_flute=>flute,pan_flute
flute_loop_sample_hook_12=>flute,samples
shaku_flute=>flute,shaku
jap_flute=>flute,shaku
traverseflute=>flute,traverse
woodcutters_flute=>flute,woodcutters
american_folk_song=>folk,american
found=>found_sounds
basement_freestyle=>freestyle
freestyle_mix=>freestyle
freejazz=>free_jazz
funk_melody=>funk
old_funk=>funk
funk_hiphopcrisy=>funk
minimal_funk=>funk
newfunk=>funk
dark_funk=>funk
slow_funk=>funk
boarding_school_funk=>funk
neurofunk=>funk
funk_chill=>funk,chill
discofunk=>funk,disco
funk_fusion=>funk,fusion
funk_groove_psychedelic_e=>funk,groove,psychedelic
jazz_funk=>funk,jazz
latin_funk=>funk,latin
philosophical_funk=>funk,philosophical
prog_funk=>funk,progressive
funk_rock=>funk,rock
chopfunk=>funk,sliced
tribal_funk=>funk,tribal
funked_up=>funky
funky_purgatory=>funky
xanadu_funky=>funky
big_ass_afro=>funky
funkyish=>funky
remix_funky_breaks_groovy=>funky,breaks
chilled_funky_dark=>funky,chill
funky_classical=>funky,classical
classical_funky_instrumen=>funky,classical,instrumental
funky_downtempo=>funky,downtempo
funky_sacramento=>funky,sacramento
funky_soul_groove=>funky,soul
jazz_fusion=>fusion
jazz_rock=>fusion
apple_macintosh_garage_ba=>garageband
apple_loops=>garageband
apple_garageband_80sdance=>garageband
apple_garageband_drums_ch=>garageband
german_accent=>german
electronic_glitchy_jazz_a=>giitchy,jazzy
glitchy=>glitch
artifact_beats=>glitchy
amens=>gospel
gothic=>goth
gothiky_disco=>goth,disco
granular=>granular_sythensis
s_groove=>groove
guitar_body=>guitar
well_lots_of_guitar=>guitar
guitar_not_much_else=>guitar
guitare=>guitar
forwards_guitar=>guitar
out_of_tune_guitar=>guitar
guitars=>guitar
more_guitar=>guitar
12_string_acoustic_guitar=>guitar,12_string
acoustic_guitar=>guitar,acoustic
accoustic_guitar=>guitar,acoustic
guitar_acoustic=>guitar,acoustic
steel_guitar=>guitar,acoustic
nylong_string_guitar=>guitar,acoustic,nylon_string
nylon_guitar=>guitar,acoustic,nylon_string
nylon=>guitar,acoustic,nylon_string
nylon_string_guitar=>guitar,acoustic,nylon_string
nylonstringguitar=>guitar,acoustic,nylon_string
classicalguitar=>guitar,acoustic,nylon_string
classical_guitar=>guitar,acoustic,nylon_string
spanish_guitar=>guitar,acoustic,spanish
acousticguitar=>guitar,acoustic_guitar
angry_guitar=>guitar,angry
bagpipes_guitar=>guitar,bagpipes
blues_guitar=>guitar,blues
guitar_baby=>guitar,children
clean_guitars=>guitar,clean
guitar_duo=>guitar,dio
distorted_guitar=>guitar,distorted
overdriven_guitars=>guitar,distortion
echo_guitar=>guitar,echo
delay_guitars=>guitar,echo
guitarfx=>guitar,effects
electric_guitar=>guitar,electric
electric_guitars=>guitar,electric
elec_guitar=>guitar,electric
stratocaster=>guitar,electric,strat
electricguitar=>guitar,electric_guitar
electric_guitar_noise_amb=>guitar,electric_guitar
elecctric_guitar=>guitar,electric_guitar
funky_electric_guitar=>guitar,electric_guitar,funky
hondo_electric_guitar=>guitar,electric_guitar,hondo
telecaster=>guitar,electric_guitar,telecaster
fender_guitars=>guitar,fender
fretlessguitar=>guitar,fretless
guitar_noise=>guitar,fret_noise,noise
guitar_funky=>guitar,funky
heavy_guitar=>guitar,heavy
heavy_guitars=>guitar,heavy
facemelting_guitars=>guitar,heavy
heavy_guitar_backbone=>guitar,heavy
metal_guitar=>guitar,heavy_metal
instrumental_guitar=>guitar,instrumental
jazz_guitar=>guitar,jazz
jazzguitar=>guitar,jazz
guitar_jazz_psychedelic_r=>guitar,jazz,psychedelic
muted_guitar=>guitar,muted
more_guitar_noise=>guitar,noise
baritone_guitaroboe=>guitar,oboe
rock_guitar=>guitar,rock
guitarsampled=>guitar,samples
guitar_sample=>guitar,samples
recycledguitar=>guitar,samples
scary_guitar=>guitar,scary
slide=>guitar,slide_guitar
soaring_guitar=>guitar,soaring
lead=>guitar,solo
lead_guitar=>guitar,solo
more_lead_guitar=>guitar,solo
guitar_solo=>guitar,solo
space_guitars=>guitar,spac
guitar_and_violin=>guitar,violin
s_guitar_and_vocal=>guitar,vocals
wah_wah_guitar=>guitar,wah_wah
blues_hammond=>hammond,blues
hammond_organ=>hammond,organ
hardcore_rock=>hardcore,rock
blues_harp=>harmonica,blues
s_harp=>harp
harp_loop_120_bpm_backgro=>harp
harp_waves_birds_clean=>harp,bird
mondharp=>harp,mondharp
welsh_harp=>harp,welsh_harp
harpsicord=>harpsichord
harspichord=>harpsichord
harpsichrord=>harpsichord
harpiscord=>harpsichord
metal=>heavy_metal
doom_metal_remix_ciggibur=>heavy_metal,doom
hip=>hip_hop
hip_hop_remix=>hip_hop
hip_hop_vadim_99_bpm=>hip_hop
hip_hop_beats=>hip_hop
hop=>hip_hop
hiphop=>hip_hop
hip_hop_fort_minor=>hip_hop
heavy_hop=>hip_hop
real_hip_hop=>hip_hop
to_hip_hop=>hip_hop
hiphopish=>hip_hop
changerhiphopmusic=>hip_hop
abstract_hip_hop=>hip_hop,abstract
hiphop_electronica_abstra=>hip_hop,abstract
abstract_hiphop=>hip_hop,abstract
alternative_hiphop=>hip_hop,alternative
chicago_hip_hop=>hip_hop,chicago
drone_hop=>hip_hop,drone
explorative_hip_hop=>hip_hop,exploration
funk_hop=>hip_hop,funk
hiphop_instrumental=>hip_hop,instrumental
instrumental_hip_hop_trac=>hip_hop,instrumental
jazzy_hip=>hip_hop,jazzy
hiphop_jazz_jazzy=>hip_hop,jazzy
electric_jazzhop=>hip_hop,jazzy
bebop_meets_hip_hop=>hip_hop,jazzy
jazz_hop=>hip_hop,jazzy
hop_female_vocals=>hip_hop,male_vocals
hip_hop_male_vocals_guita=>hip_hop,male_vocals
new_york_hip_hop=>hip_hop,new_york
poetic_hip_hop=>hip_hop,poetry
hiphop_pl=>hip_hop,polish
hip_hop_r_b=>hip_hop,r_n_b
underground_hip_hop=>hip_hop,soundtrack
hihat=>hit_hat
highhat=>hi_hat
high_hat=>hi_hat
hihats=>hi_hat
hats=>hi_hat
hi_high_hat=>hi_hat
hi_hats=>hi_hat
hat=>hi_hat
hi_hat_closed=>hi_hat,closed_hi_hat
closed_high_hat=>hi_hat,closed_hi_hat
closed_hh_3=>hi_hat,closed_hi_hat
closed_hh=>hi_hat,closed_hi_hat
open_hh=>hi_hat,open_hi_hat
pedal_hh=>hi_hat,pedal_hi_hat
horns=>horn
horror_music=>horror
funky_house=>house
housey=>house
house_music=>house
acid_house=>house,acid_house
booty_house=>house,booty
house_dance=>house,dance
deep_house=>house,deep
deephouse=>house,deep
electro_house=>house,electro
electrohouse=>house,electro
electronic_house=>house,electronic
euro_house=>house,euro
garage_house=>house,garage
latin_house=>house,latin
micro_house=>house,micro
old_school_house=>house,old_school
progressive_house=>house,progressive
progg_house=>house,progressive
synth_hip_house=>house,synth
electronic_tribal_house=>house,tribal
vocal_house=>house,vocals
ambient_idm_cubik_vocoid_=>idm,ambient_flavor
garage_idm=>idm,garage
ilbiebt=>illbient
ilbient=>illbient
india=>indian
electronic_industrial_fem=>industrial
electronic_industrial=>industrial
instru=>instrumental
mellow_instrumental=>instrumental
experimental_instrumental=>instrumental
nonvocal=>instrumental
instrumenta=>instrumental
hiphop_instrumental_remix=>instrumental
instrumentation=>instrumental
jess_beat_instrumental=>instrumental
vocalless=>instrumental
instrumentals=>instrumental
instrumental_music=>instrumental
rap_instrumental=>instrumental
instumental=>instrumental
intrumental=>instrumental
istrumental=>instrumental
instrumental_stems=>instrumental
electro_instrumental_too_=>instrumental
melody_pop_instrumental=>instrumental,pop
instrumental_trumpet=>instrumental,trumpet
electric_jaw_harp=>jaw_harp
jawharp=>jaw_harp
indo_jazz_fusion=>jazz
funky_jazz=>jazz,funky
latin_jazz=>jazz,latin
jazz_quartet=>jazz,quartet
samba_jazz=>jazz,samba
jazz_trio=>jazz,trio
jazz_singer=>jazz,vocals
jazz_mic=>jazzy
jazzy_beats=>jazzy
cool_jazzy_beat=>jazzy
jazzlike=>jazzy
s_jazz=>jazzy
jazz_tune_remix_loops_fem=>jazzy
jazzesque=>jazzy
musetta_tijs_remix_jazz_e=>jazzy
jazz_ish=>jazzy
jazzy_downbeat=>jazzy,downbeat
jazz_rhodes_bass=>jazzy,rhodes,bass
smooth_jazzish=>jazzy,smooth
urban_freeform_jazz=>jazzy,urban
electronic_jungle=>jungle
keys=>keyboards
bass_drum=>kick
killkillkill=>kill_kill_kill
female_laughter=>laughter
loop=>loops
tounge=>lounge
classical_lounge_chill=>lounge,chill
jazz_lounge=>lounge,jazzy
16thcenturylute=>lute
male_vocales=>male_vocals
male_vocals_with_a_bit_d=>male_vocals
maleleadvocal=>male_vocals
male_lead_vocal=>male_vocals
male_lead_vocals=>male_vocals
male__vocal=>male_vocals
male_vocal=>male_vocals
male_vox=>male_vocals
male_vocals_acapella_poem=>male_vocals
male_vocals_outofit=>male_vocals
melodymale_vocals=>male_vocals
male_vocs=>male_vocals
male_voice=>male_vocals
male_volcals=>male_vocals
man=>male_vocals
male_vocals_remix=>male_vocals
male_voc=>male_vocals
male=>male_vocals
male_vocak=>male_vocals
male_vocals_r=>male_vocals
male_vocals_ballad_r=>male_vocals,ballad
male_chant=>male_vocals,chant
downtempo_male_vocals=>male_vocals,downtempo
male_vocals_downtempo=>male_vocals,downtempo
male_vocals_electro=>male_vocals,electro
male_group=>male_vocals,group
male_vocals_poetry=>male_vocals,poetry
male_vocals_poetry_acapel=>male_vocals,poetry
male_rap=>male_vocals,rap
male_vocal_rap=>male_vocals,rap
male_vocals_reggae=>male_vocals,reggae
male_vocals_rock=>male_vocals,rock
rock_male_vocals=>male_vocals,rock
male_spoken_words=>male_vocals,spoken_word
mbira=>marimba
accidental_mash=>mashup
mash=>mash_up
mashup=>mash_up
electronic_metal=>metal,electronic
middle_eastern_beats=>middle_east
musical_stageshow=>musical,stageshow
concrete=>musique_concrete
american_indian=>native_american
neosoul=>neo_soul
age=>new age
newage=>new_age
ninja_jazz=>ninja,nu_jazz
nsfw_en_francais=>nsfw
nujazz=>nu_jazz
oldschool=>old_school
old_school_vibe=>old_school
anatolian_strings=>orchestral
symphony=>orchestral
orchestra=>orchestral
orchestral_string=>orchestral
orchestration=>orchestral
symphonic=>orchestral
orchestral_strings=>orchestral
strings_classical_77bpm_o=>orchestral
hammond_leslie_organ=>organ,hammond,leslie
out_of_it=>outofit
pad=>pads
percs=>percussion
percussions=>percussion
war_zone_percussion_bass_=>percussion
perc=>percussion
latin_percussion=>percussion,latin
tuned_percussion=>percussion,tuned
midnight_piano_bridge=>piano
piano_insert=>piano
prepared_piano=>piano
high_quality_piano_sample=>piano
piano_lesson_kirby_electr=>piano
120bmp_piano_evanescence_=>piano
grandpiano=>piano,acoustic
concert_piano=>piano,acoustic
piano_classical_sketch_sc=>piano,acoustic
grand_piano=>piano,acoustic,grand_piano
uprightpiano=>piano,acoustic,upright
piano_ambient_acoustic_wa=>piano,ambient_flavor
old_piano=>piano,antique
antique_piano=>piano,antique
piano_classic_classical=>piano,classical
piano_classical_scales_mi=>piano,classical
piano_classical_with_drum=>piano,classical
piano_original_classical_=>piano,classical
piano_classical_octaves=>piano,classical
piano_classical_piano_wav=>piano,classical
classical_classic_piano_s=>piano,classical
scales_piano_classical_sk=>piano,classical
piano_loop_120bpm_distort=>piano,distorted
epiano=>piano,electric,electric_piano
e_piano=>piano,electric_piano
electri_piano=>piano,electric_piano
gated_piano=>piano,gated
honkytonk_piano=>piano,honkytonk
jazz_piano=>piano,jazz
piano_loop=>piano,loops
piano_loop_uptempo_fast_h=>piano,loops
piano_sample=>piano,loops
loops_mellow_piano_string=>piano,mellow,orchestral
strings_piano=>piano,orchestral
piano_rock=>piano,rock
sad_dark_and_light_piano_=>piano,sad,dark
piano_solo=>piano,solo
solo_piano=>piano,solo
swing_piano_vocal_melody_=>piano,swing,vocals
piano_solo_strings=>piano,violin
pizz=>pizzicatto
beatpop=>pop
electropop=>pop,electro
pop_female_vocals=>pop,female_vocals
pop_latin_lamida=>pop,latin
rock_pop=>pop_rock
progresive=>progressive
prog=>progressive
progressiv=>progressive
proggresive_rock=>progressive_rock
prog_rock=>progressive_rock
electronic_psychedelic=>psychedelic
psychadelic=>psychedelic
funk_punk=>punk
art_punk=>punk,arty
punk_post_acid_ska=>punk,ska
jazzy_ragga_experiment=>ragga,jazzy
raggajungle=>ragga,jungle
rap_90bpm=>rap
acappella_rap=>rap
2_rappers=>rap
rap_sacramento_angry_rap_=>rap, sacramento, angry
ethnic_rap=>rap,ethnic
rap_funk=>rap,funk
gangster_rap=>rap,ganster
jazz_rap=>rap,jazzy
rap_male_vocals=>rap,male_vocals
rap_mean_girl=>rap,mean
rap_loop_98bpm_orchestral=>rap,orchestral
pop_conscious_rap=>rap,pop
rap_rnb_world_electro=>rap,r_n_b
acapella_rap_uk=>rap,uk
reggie=>reggae
midnight_reggae=>reggae
reggea=>reggae
with_reggae_reggae_sauce_=>reggae
suedmilch_ruggea=>reggae
reggae_dancehall_female_v=>reggae
pseudoreggae=>reggae
ruggea=>reggae
free_reggae=>reggae
reggae_roote=>reggae
regge=>reggae
reggae_drumset=>reggae,drums
reggae_loop_dub_instrumen=>reggae,instrumental
raggaeton=>reggaeton
mix=>remix
reversed=>reverse
backward=>reversed
backwards=>reversed
rodes=>rhodes
fender_rhodes=>rhodes
electric_rock=>rock
ambient_rock=>rock
alternative_rock=>rock,alternative
alt_rock=>rock,alternative
avantronik_rock=>rock,avant_garde
electronic_rock=>rock,electronic
indie_rock=>rock,indie
roll=>rock_roll
r_b=>r_n_b
rnb=>r_n_b
sad_time_friends_female_i=>sad
alsa=>salsa
sampling=>sampler
sampled=>sampler
appropriation=>sampling
sax=>saxophone
saxophones=>saxophone
saxofoon=>saxophone
saxo=>saxophone
saxes=>saxophone
saxophon=>saxophone
laidback_sax=>saxophone
saxen=>saxophone
saxaphone=>saxophone
alto=>saxophone,alto_saxophone
sax_alto=>saxophone,alto_saxophone
alto_sax=>saxophone,alto_saxophone
alto_adige=>saxophone,alto_saxophone
baritone=>saxophone,baritone_saxophone
bari=>saxophone,baritone_saxophone
soprano=>saxophone,soprano_saxophone
sopransaxophon=>saxophone,soprano_saxophone
sopran_sax=>saxophone,soprano_saxophone
soprano_saxophone=>saxophone,soprano_saxophone
tenor_sax=>saxophone,tenor_saxophone
tenor=>saxophone,tenor_saxophone
school=>school_ensemble
ensemble=>school_ensemble
scratchy_bits=>scratching
scratches=>scratching
scratch=>scratching
secretsanta=>secret_mixter
secret=>secret_mixter
secretmixter=>secret_mixter
shakers=>shaker
beyond_shoe_gaze=>shoe_gaze
beatcutter_beat=>sliced
beat_chopping=>sliced
chop=>sliced
slicer=>sliced
slice=>sliced
smooth_jazz_hip_hop_guita=>smooth,guitar
and_soulfull=>soul
and_soul=>soul
bedroom_soul=>soul
film_music=>soundtrack
filmmusic=>soundtrack
filmic=>soundtrack
sound_track=>soundtrack
sountrack=>soundtrack
film=>soundtrack
film_soundtrack=>soundtrack
film_noir=>soundtrack,film_noir
spokenword=>spoken_word
apoken_word=>spoken_word
word=>spoken_word
spoken=>spoken_word
spoken_word_promo=>spoken_word
spoken_words=>spoken_word
talking=>spoken_word
electronic_spoken_word=>spoken_word
words=>spoken_word
strum=>strumming
strummy=>strumming
guitar_strum=>strumming,guitar
bending_synth_sample_loop=>synthesizer
sythn=>synthesizer
synths=>synthesizer
synth=>synthesizer
synth1=>synthesizer
analog_synth=>synthesizer,analog
synth_bass=>synthesizer,bass
synth_fx=>synthesizer,effects
synth_strings=>synthesizer,fake_strings
synth_guitar=>synthesizer,guitar
synth_pads=>synthesizer,pads
synth_lead=>synthesizer,solo
tablas=>tabla
wonky_tekno=>techno
demential_techno=>techno
tecno=>techno
industrial_techno=>techno,industrial
radio_gaga_telephone_male=>telephone
theramin=>theremin
thunderstorm=>thunder
angry_topical=>topical,antry
blue_trance=>trance
ambient_trance=>trance
triphop=>trip_hop
trip_hop_mommaluv=>trip_hop
trip_hop_ambient_dark_pia=>trip_hop,ambient_flavor
trip_hop_concept=>trip_hop,conceptual
bass_trombone=>trombone
trombon_bassoon=>trombone,bassoon
trompet=>trumpet
trumpetyness=>trumpet
trumpety=>trumpet
trumpets=>trumpet
jazzy_trumpet=>trumpet,jazz
muted_trumpet=>trumpet,muted
funky_samba_thrumpet_sax_=>trumpet,saxophone,funky,samba
vinyl_funk=>turntables
vinyl=>turntables
alt_urban=>urban,alternative
vibes=>vibrophone
violins=>violin
violon=>violin
string=>violin
strings=>violin,orchestral
language=>vocals
singing=>vocals
beautiful_voice=>vocals
vox=>vocals
voices=>vocals
adaptable_vocals=>vocals
good_vocals=>vocals
vocal=>vocals
vocal_source_track=>vocals
acapella_remix=>vocals
voice_recording=>vocals
vocals_acappella=>vocals
talk=>vocals
voice=>vocals
singin=>vocals
singer=>vocals
androgynous_vocals=>vocals
vocal_mix=>vocals
arabian_voices=>vocals,arabian
backin_vocs=>vocals,backing
backing_vox=>vocals,backing
backing_vox_and_harmonies=>vocals,backing
backing_vocs=>vocals,backing
blues_vocal=>vocals,blues
vocoders=>vocoder
vocode=>vocoder
wah=>wah_wah
whah_guitar=>wah_wah,guitar
wah_guitar=>wah_wah,guitar
wahguitar=>wah_wah,guitar
whawah=>wah_wah,guitar
wha_wah=>wah_wah,guitar
wahwah=>wah_wah,guitar
wha_wha=>wah_wah,guitar
3_4time=>waltz
whatnot=>whatever
elektronik_afrowhatever=>whatever
whatsemecallit=>whatever
whistle=>whistles
the_white_cube_project=>white_cube
white_cube_remix_project=>white_cube
whitecube=>white_cube
the_white_cube=>white_cube
the_white_cube_remix_proj=>white_cube
woodwind=>woodwinds
world_music=>world
worldbeat=>world
world_beat=>world
wurli=>wurlitzer
*/
?>