<?/* This file was generated by ccHost Content Manager 
[meta]
     type = dynamic_content_page
     desc = _('Artist Spotlight Q & A')
      t = ccskins/shared/pages/content_page.tpl
      content_page_columns = 1
      limit = 1
      content_page_width = 830px
      content_page_textformat = format
      content_page_paging = 1
      content_page_box = 0
      sort = date
      ord = asc
      content_feed = 1
      topic_type = artist_qa

[/meta]
*/
$A['content_page_box'] = '0';
$A['content_page_paging'] = '1';
$A['content_page_width'] = '830px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '1';
$id = empty($_GET['ids']) ? '' : $_GET['ids'];
$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Artist Spotlight Q & A</h1>";
cc_query_fmt('f=page&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=artist_qa&limit=1' . $id . '&topic=' . $topic );
$A['macro_names'][] = 'prev_next_links';
 cc_content_feed('datasource=topics&type=artist_qa&page=artist-spotlight-q-a','Artist Spotlight Q & A','topics');
?>