<?/* This file was generated by ccHost Content Manager 
[meta]
     type = dynamic_content_page
     desc = _('Find Music')
      t = ccskins/shared/pages/content_page.tpl
      content_page_columns = 2
      limit = 
      content_page_width = 700px
      content_page_textformat = format
      content_page_paging = 1
      content_page_box = 1
      sort = date
      ord = asc
      topic_type = findmusic

[/meta]
*/
$A['content_page_box'] = '1';
$A['content_page_paging'] = '1';
$A['content_page_width'] = '700px';
$A['content_page_textformat'] = 'format';
$A['content_page_columns'] = '2';
$id = empty($_GET['ids']) ? '' : $_GET['ids'];
$topic = empty($_GET['topic']) ? '' : $_GET['topic'];
print "<h1>Find Music</h1>";
cc_query_fmt('f=page&t=ccskins/shared/pages/content_page.tpl&sort=date&ord=asc&type=findmusic&limit=' . $id . '&topic=' . $topic );
$A['macro_names'][] = 'prev_next_links';
?>